# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Work/cliff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Work/cliff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Work/cliff/CMakeFiles /mnt/c/Work/cliff//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Work/cliff/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cliff

# Build rule for target.
cliff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cliff
.PHONY : cliff

# fast build rule for target.
cliff/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/build
.PHONY : cliff/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/main.c.s
.PHONY : main.c.s

src/debug.o: src/debug.c.o
.PHONY : src/debug.o

# target to build an object file
src/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/debug.c.o
.PHONY : src/debug.c.o

src/debug.i: src/debug.c.i
.PHONY : src/debug.i

# target to preprocess a source file
src/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/debug.c.i
.PHONY : src/debug.c.i

src/debug.s: src/debug.c.s
.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/debug.c.s
.PHONY : src/debug.c.s

src/lexer/keyword.o: src/lexer/keyword.c.o
.PHONY : src/lexer/keyword.o

# target to build an object file
src/lexer/keyword.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/keyword.c.o
.PHONY : src/lexer/keyword.c.o

src/lexer/keyword.i: src/lexer/keyword.c.i
.PHONY : src/lexer/keyword.i

# target to preprocess a source file
src/lexer/keyword.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/keyword.c.i
.PHONY : src/lexer/keyword.c.i

src/lexer/keyword.s: src/lexer/keyword.c.s
.PHONY : src/lexer/keyword.s

# target to generate assembly for a file
src/lexer/keyword.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/keyword.c.s
.PHONY : src/lexer/keyword.c.s

src/lexer/lexer.o: src/lexer/lexer.c.o
.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/lexer.c.o
.PHONY : src/lexer/lexer.c.o

src/lexer/lexer.i: src/lexer/lexer.c.i
.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/lexer.c.i
.PHONY : src/lexer/lexer.c.i

src/lexer/lexer.s: src/lexer/lexer.c.s
.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/lexer.c.s
.PHONY : src/lexer/lexer.c.s

src/lexer/token.o: src/lexer/token.c.o
.PHONY : src/lexer/token.o

# target to build an object file
src/lexer/token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/token.c.o
.PHONY : src/lexer/token.c.o

src/lexer/token.i: src/lexer/token.c.i
.PHONY : src/lexer/token.i

# target to preprocess a source file
src/lexer/token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/token.c.i
.PHONY : src/lexer/token.c.i

src/lexer/token.s: src/lexer/token.c.s
.PHONY : src/lexer/token.s

# target to generate assembly for a file
src/lexer/token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/lexer/token.c.s
.PHONY : src/lexer/token.c.s

src/parser/expression.o: src/parser/expression.c.o
.PHONY : src/parser/expression.o

# target to build an object file
src/parser/expression.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/expression.c.o
.PHONY : src/parser/expression.c.o

src/parser/expression.i: src/parser/expression.c.i
.PHONY : src/parser/expression.i

# target to preprocess a source file
src/parser/expression.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/expression.c.i
.PHONY : src/parser/expression.c.i

src/parser/expression.s: src/parser/expression.c.s
.PHONY : src/parser/expression.s

# target to generate assembly for a file
src/parser/expression.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/expression.c.s
.PHONY : src/parser/expression.c.s

src/parser/parse_tree.o: src/parser/parse_tree.c.o
.PHONY : src/parser/parse_tree.o

# target to build an object file
src/parser/parse_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/parse_tree.c.o
.PHONY : src/parser/parse_tree.c.o

src/parser/parse_tree.i: src/parser/parse_tree.c.i
.PHONY : src/parser/parse_tree.i

# target to preprocess a source file
src/parser/parse_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/parse_tree.c.i
.PHONY : src/parser/parse_tree.c.i

src/parser/parse_tree.s: src/parser/parse_tree.c.s
.PHONY : src/parser/parse_tree.s

# target to generate assembly for a file
src/parser/parse_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/parse_tree.c.s
.PHONY : src/parser/parse_tree.c.s

src/parser/parser.o: src/parser/parser.c.o
.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/parser.c.o
.PHONY : src/parser/parser.c.o

src/parser/parser.i: src/parser/parser.c.i
.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/parser.c.i
.PHONY : src/parser/parser.c.i

src/parser/parser.s: src/parser/parser.c.s
.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/parser/parser.c.s
.PHONY : src/parser/parser.c.s

src/tool/string_builder.o: src/tool/string_builder.c.o
.PHONY : src/tool/string_builder.o

# target to build an object file
src/tool/string_builder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/tool/string_builder.c.o
.PHONY : src/tool/string_builder.c.o

src/tool/string_builder.i: src/tool/string_builder.c.i
.PHONY : src/tool/string_builder.i

# target to preprocess a source file
src/tool/string_builder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/tool/string_builder.c.i
.PHONY : src/tool/string_builder.c.i

src/tool/string_builder.s: src/tool/string_builder.c.s
.PHONY : src/tool/string_builder.s

# target to generate assembly for a file
src/tool/string_builder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/tool/string_builder.c.s
.PHONY : src/tool/string_builder.c.s

src/tool/visitor.o: src/tool/visitor.c.o
.PHONY : src/tool/visitor.o

# target to build an object file
src/tool/visitor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/tool/visitor.c.o
.PHONY : src/tool/visitor.c.o

src/tool/visitor.i: src/tool/visitor.c.i
.PHONY : src/tool/visitor.i

# target to preprocess a source file
src/tool/visitor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/tool/visitor.c.i
.PHONY : src/tool/visitor.c.i

src/tool/visitor.s: src/tool/visitor.c.s
.PHONY : src/tool/visitor.s

# target to generate assembly for a file
src/tool/visitor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliff.dir/build.make CMakeFiles/cliff.dir/src/tool/visitor.c.s
.PHONY : src/tool/visitor.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cliff"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/lexer/keyword.o"
	@echo "... src/lexer/keyword.i"
	@echo "... src/lexer/keyword.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/lexer/token.o"
	@echo "... src/lexer/token.i"
	@echo "... src/lexer/token.s"
	@echo "... src/parser/expression.o"
	@echo "... src/parser/expression.i"
	@echo "... src/parser/expression.s"
	@echo "... src/parser/parse_tree.o"
	@echo "... src/parser/parse_tree.i"
	@echo "... src/parser/parse_tree.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/tool/string_builder.o"
	@echo "... src/tool/string_builder.i"
	@echo "... src/tool/string_builder.s"
	@echo "... src/tool/visitor.o"
	@echo "... src/tool/visitor.i"
	@echo "... src/tool/visitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

