#ifndef TOY_TOKEN_TYPE_H
#define TOY_TOKEN_TYPE_H


typedef enum {

	LEFT_PAREN = 0, //single character token s
	RIGHT_PAREN = 1,
	LEFT_BRACE = 2,
	RIGHT_BRACE = 3,
	LEFT_BRACKET = 4,
	RIGHT_BRACKET = 5,
	SEMICOLON = 6,
	COMMA = 7,
	PLUS = 8, //one or two character token s
	TOKEN_PLUS_EQUAL = 9,
	TOKEN_PLUS_PLUS = 10,
	MINUS = 11,
	TOKEN_MINUS_EQUAL = 12,
	TOKEN_MINUS_MINUS = 13,
	TOKEN_MINUS_MORE = 14, //MINUS_LESS is for function synta x
	STAR = 15,
	TOKEN_STAR_EQUAL = 16,
	SLASH = 17,
	TOKEN_SLASH_EQUAL = 18,
	TOKEN_MODULO = 19,
	TOKEN_MODULO_EQUAL = 20,
	BANG = 21,
	BANG_EQUAL = 22,
	EQUAL = 23,
	EQUAL_EQUAL = 24,
	EQUAL_GREATER = 25, //EQUAL_GREATER is for the arrow synta x
	GREATER = 26,
	GREATER_EQUAL = 27,
	LESS = 28,
	LESS_EQUAL = 29,
	TOKEN_AND_AND = 30,//these can single, doubl e
	TOKEN_AND = 31,
	TOKEN_OR_OR = 32,
	TOKEN_OR = 33,
	TOKEN_DOT = 34,
	TOKEN_DOT_DOT = 35,
	TOKEN_QUESTION = 36,//ternary operato r
	TOKEN_COLON = 37,
	TOKEN_IDENTIFIER = 38,//literal = 38s
	TOKEN_INT = 39,
	TOKEN_FLOAT = 40,
	STRING = 41,
	ELSE = 42,
	FALSE = 43,
	FOR = 44,
	IF = 45,
	RETURN = 47,
	TRUE = 48,
	LOOP = 49,
	FUNCTION = 50,
	TOKEN_PASS = 51, //do nothing//met a
	TOKEN_ERROR = 52,
	TOKEN_EOF = 53,
	TOKEN_END_LINE = 54,
	NILL = 55,
	NUMBER = 56,
	PRINT = 57

} TokenType;

#endif // !TOKEN_TYPE_H
