#ifndef TOY_TOKEN_TYPE_H
#define TOY_TOKEN_TYPE_H


typedef enum {
    // Single-character tokens.
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
	SEMICOLON, COMMA, PLUS, MINUS, STAR, SLASH, MODULO, BANG, EQUAL, GREATER,
	LESS, TILDA,

	// Two character tokens.
	PLUS_EQUAL, PLUS_PLUS, MINUS_EQUAL, MINUS_MINUS, MINUS_GREATER, MINUS_LESS,
	STAR_EQUAL, SLASH_EQUAL, MODULO_EQUAL, BANG_EQUAL, EQUAL_EQUAL, EQUAL_GREATER,
	GREATER_EQUAL, LESS_EQUAL, OR_GREATER,

	// Bitwise and special tokens.
	AND, AND_AND = 30,
	OR, OR_OR,
	DOT, DOT_DOT,
	QUESTION, QUESTION_QUESTION,
	COLON, COLON_COLON,

	// Literals.
	IDENTIFIER, STRING, NUMBER,

	// Keywords.
	IF, ELSE,
	TRUE, FALSE,
	FOR, LOOP, PASS,
	FUNCTION, PRINT, RETURN,
	T_EOF, END_LINE, ERROR, NILL,

} TokenType;

#endif // !TOKEN_TYPE_H
